name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug] <short description>"
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear description of what the bug is.
      placeholder: "Clicking on Submit throws a 500 error..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How do we reproduce the bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: What OS/browser/device are you using?
      placeholder: "Windows 11, Chrome 123, Firefox 115"

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or screenshots
      description: Paste logs or screenshots if applicable.
      placeholder: "Paste error logs here…"
