name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] <short description>"
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What would you like to see added or changed?
      placeholder: "I’d like to have a 'bookmark' option for posts..."
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this feature useful?
      description: Explain how this improves the user experience or project value.
      placeholder: "This would help users save posts for later reading..."

  - type: input
    id: related
    attributes:
      label: Related Issues or PRs
      description: Link to any existing discussion, issue, or pull request.
